services:
  # kafka broker (kraft mode)
  kafka:
    image: apache/kafka:latest
    container_name: kafka-lab
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      
      # listeners configuration:
      # 1. controller (9093): internal cluster management
      # 2. internal (29092): communication between containers (kafka ui)
      # 3. external (9092): external access (host machine/apps)
      KAFKA_LISTENERS: CONTROLLER://0.0.0.0:9093,INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      
      # advertised listeners (what clients see):
      # internal: kafka-lab:29092 (for docker network)
      # external: localhost:9092 (for your local java apps)
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-lab:29092,EXTERNAL://localhost:9092
      
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-lab:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      # critical fix for single-node cluster:
      # prevents "offsets topic not found" loop by setting replication to 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  # Interface Visual para o Kafka
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka

  # Banco de Dados para persistÃªncia dos logs de envio
  db:
    image: postgres:15
    container_name: postgres-lab
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webhook_db
    ports:
      - "5432:5432"
